### ISSUE TITLE
你好同学

### ISSUE THREAD

**Issue by usodonkey** [FesianXu/SK-CNN#2]
我初学深度学习 想请教以下怎么训练和测试您这个代码呢？

**Comment by FesianXu** [comment]
firstly, you need to at least be familiar with python3.6 and then learn the deep learning framework Keras, But dont worry about keras since it is a really simple and friendly deep learning framework. Once you learn the above things, you can start to read the code.  i have not evaluated my code on NTU-RGBD, but if you want you can modify the data loading corresponding code, `_train_x_generator()`. Maybe you will want to get more information about the dataloader in keras, please google it.
